### ISSUE TITLE
something is not working

### ISSUE THREAD

**Issue by shanow7** [Euronymou5/SEO#1]
--------------------------------------------
      |        ███████ ███████  ██████           |
      |        ██      ██      ██    ██          |
      |        ███████ █████   ██    ██          |
      |             ██ ██      ██    ██          |
      |        ███████ ███████  ██████           |
      |                                          | 
      |                v1.0                      |
      ------ :[ Scorpion Email Osint] : ----------

[-] Introduce un email: registrar-abuse@google.com

[?] Valido: Email invalido

can you help?

**Comment by Euronymou5** [comment]
If you put another email, it still gives you an error?

**Comment by shanow7** [comment]
yes

**Comment by Euronymou5** [comment]
Did you follow the installation process to the letter?

**Comment by shanow7** [comment]
yes
